apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: global.ng.enabled
  name: cv-nextgen
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.23.0
- condition: global.ng.enabled
  name: le-nextgen
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.3.0
- condition: global.cg.enabled
  name: learning-engine
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.3.0
- condition: global.cg.enabled
  name: verification-svc
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.42.0
- condition: global.ng.enabled
  name: srm-ui
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.5.0
description: Helm chart for Harness SRM
name: srm
type: application
version: 0.20.0
