apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: global.ng.enabled
  name: cv-nextgen
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.37.1
- condition: global.ng.enabled
  name: le-nextgen
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.8.0
- condition: global.ng.enabled
  name: srm-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.12.0
description: Helm chart for Harness SRM
name: srm
type: application
version: 0.28.1
