apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: global.ng.enabled
  name: cv-nextgen
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.48.2
- condition: global.ng.enabled
  name: le-nextgen
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.10.0
- condition: global.ng.enabled
  name: srm-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.13.1
description: Helm chart for Harness SRM
name: srm
type: application
version: 0.34.0
