apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: global.ng.enabled
  name: cv-nextgen
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.49.0-snapshot-2025-11-13-11-25-59-b45673
- condition: global.ng.enabled
  name: le-nextgen
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.10.0-snapshot-2025-11-13-11-25-59-f37591
- condition: global.ng.enabled
  name: srm-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.14.0-snapshot-2025-11-13-11-25-59-46b726
description: Helm chart for Harness SRM
name: srm
type: application
version: 0.34.0
