apiVersion: v2
appVersion: 1.546.0
dependencies:
- name: event-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.17.0
- name: anomaly-detection
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.26.1
- name: cloud-info
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.15.2
- name: telescopes
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.7.2
- name: batch-processing
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.86.7
- name: ng-ce-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.84.1
- name: ce-nextgen
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.88.6
description: A Helm chart for Harness Cloud Cost Management (CCM) module
name: ccm
type: application
version: 0.41.0
