apiVersion: v2
appVersion: 1.546.0
dependencies:
- name: event-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.12.4
- name: anomaly-detection
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.4.0
- name: cloud-info
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.7.0
- name: telescopes
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.3.2
- name: batch-processing
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.31.2
- name: ng-ce-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.31.5
- name: ce-nextgen
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.34.4
description: A Helm chart for Harness Cloud Cost Management (CCM) module
name: ccm
type: application
version: 0.24.0
