apiVersion: v2
appVersion: 1.546.0
dependencies:
- name: event-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.16.0
- name: anomaly-detection
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.26.1
- name: cloud-info
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.15.1
- name: telescopes
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.7.2
- name: batch-processing
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.85.4
- name: ng-ce-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.83.8
- name: ce-nextgen
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.87.1
description: A Helm chart for Harness Cloud Cost Management (CCM) module
name: ccm
type: application
version: 0.39.0
