apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: global.gitops.enabled
  name: gitops
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.17.9
description: Helm chart for Harness CD
name: cd
type: application
version: 0.21.0
