apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: global.cd.enabled
  name: gitops
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.47.4-snapshot-2026-01-12-06-00-34-c62976
description: Helm chart for Harness CD
name: cd
type: application
version: 0.35.7
