apiVersion: v2
appVersion: 0.1.0
dependencies:
- condition: global.smpUdp.enabled
  name: config-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 0.1.155
- condition: global.smpUdp.enabled
  name: schema-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 0.20.0
- condition: global.smpUdp.enabled
  name: onboarding-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 0.10.249
- condition: global.smpUdp.enabled
  name: query-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 0.60.4
- condition: global.smpUdp.enabled
  name: dashboard-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.63.0
description: A Helm chart for Harness SMP UDP services
name: smp-udp
type: application
version: 0.45.0
