apiVersion: v1
kind: Secret
metadata:
  name: udp-shared-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: udp-shared-secret
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: unified-data-platform
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
type: Opaque
{{ printf "%s:" "data" }}
  AUTHZ_SERVICE_SECRET: {{ .Values.unifiedDataPlatform.authzServiceSecretValueDefault | b64enc | quote }}
  UDP_INTERNAL_SECRET: {{ .Values.unifiedDataPlatform.udpInternalSecretValueDefault | b64enc | quote }}
