apiVersion: v2
appVersion: 1.0.80220
dependencies:
- condition: global.ccm.enabled
  name: ccm
  repository: https://harness.github.io/helm-charts
  version: 0.9.0
- condition: global.cd.enabled
  name: cd
  repository: https://harness.github.io/helm-charts
  version: 0.9.0
- condition: global.cet.enabled
  name: cet
  repository: https://harness.github.io/helm-charts
  version: 0.9.0
- condition: global.chaos.enabled
  name: chaos
  repository: https://harness.github.io/helm-charts
  version: 0.9.0
- condition: global.ci.enabled
  name: ci
  repository: https://harness.github.io/helm-charts
  version: 0.9.0
- condition: global.ff.enabled
  name: ff
  repository: https://harness.github.io/helm-charts
  version: 0.9.0
- name: platform
  repository: https://harness.github.io/helm-charts
  version: 0.9.0
- condition: global.srm.enabled
  name: srm
  repository: https://harness.github.io/helm-charts
  version: 0.9.0
- condition: global.sto.enabled
  name: sto
  repository: https://harness.github.io/helm-charts
  version: 0.9.0
description: Helm Chart for deploying Harness.
name: harness
type: application
version: 0.9.0
