apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: ci-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.107.2-snapshot-2025-11-13-11-25-59-70791e
- condition: global.ti.enabled
  name: ti-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.56.9-snapshot-2025-11-13-11-25-59-e56d21
description: A Helm chart for Kubernetes
name: ci
type: application
version: 0.34.0
