apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: ci-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.108.4-snapshot-2025-11-20-00-00-49-57c55a
- condition: global.ti.enabled
  name: ti-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.56.9-snapshot-2025-11-20-00-00-49-6eea9b
description: A Helm chart for Kubernetes
name: ci
type: application
version: 0.34.0
