apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: ci-manager
  repository: https://harness.github.io/services/placeholder
  version: 0.8.0
- condition: global.ng.enabled
  name: ti-service
  repository: https://harness.github.io/services/placeholder
  version: 0.8.0
description: A Helm chart for Kubernetes
name: ci
type: application
version: 0.6.0
