apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: ci-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.116.2-vault-integration-f25ffc
- condition: global.ti.enabled
  name: ti-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.59.0-vault-integration-65b51f
description: A Helm chart for Kubernetes
name: ci
type: application
version: 0.35.0
