apiVersion: v2
appVersion: 1.25.0
dependencies:
- condition: global.code.enabled
  name: code-api
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.69.2-snapshot-2025-12-08-00-00-35-94a96d
- condition: global.code.enabled
  name: code-gitrpc
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.69.0-snapshot-2025-12-08-00-00-35-94a96d
- condition: global.code.enabled
  name: code-githa
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.69.0-snapshot-2025-12-08-00-00-35-94a96d
- condition: global.code.enabled
  name: code-search
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.69.0-snapshot-2025-12-08-00-00-35-94a96d
description: A Helm chart for Harness CODE
name: code
type: application
version: 0.35.0
