apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: global.ssca.enabled
  name: ssca-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.46.12-snapshot-2025-12-08-06-00-29-587cb8
- condition: global.ssca.enabled
  name: ssca-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 0.36.2-snapshot-2025-12-08-06-00-29-bb3ec4
description: A Helm chart for Harness SSCA
name: ssca
type: application
version: 0.35.0
