apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: global.ssca.enabled
  name: ssca-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.46.4-snapshot-2025-11-14-08-34-16-fe26f5
- condition: global.ssca.enabled
  name: ssca-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 0.36.0-snapshot-2025-11-14-08-34-16-d487a8
description: A Helm chart for Harness SSCA
name: ssca
type: application
version: 0.34.0
