config-service:
  configService:
    image:
      tagOverride: "0.1.132"
    kafka:
      enabled: false
      tlsUserSecret: ""
      tlsTruststoreSecret: ""

schema-service:
  schemaService:
    image:
      tagOverride: "0.13.9"
    kafka:
      enabled: false
      tlsUserSecret: ""
      tlsTruststoreSecret: ""
