config-service:
  configService:
    kafka:
      enabled: false
      tlsUserSecret: ""
      tlsTruststoreSecret: ""
  secrets:
    udpInternalSecret:
      secretName: query-service-ext-secret-0
      key: UDP_INTERNAL_SECRET
    authzServiceSecret:
      secretName: ng-manager-ext-secret-0
      key: NEXT_GEN_MANAGER_SECRET
      optional: true

schema-service:
  schemaService:
    kafka:
      enabled: false
      tlsUserSecret: ""
      tlsTruststoreSecret: ""
  secrets:
    udpInternalSecret:
      secretName: query-service-ext-secret-0
      key: UDP_INTERNAL_SECRET
    authzServiceSecret:
      secretName: ng-manager-ext-secret-0
      key: NEXT_GEN_MANAGER_SECRET
      optional: true

onboarding-service:
  onboardingService:
    kafka:
      enabled: false
      tlsUserSecret: ""
      tlsTruststoreSecret: ""
  secrets:
    udpInternalSecret:
      secretName: query-service-ext-secret-0
      key: UDP_INTERNAL_SECRET

query-service:
  queryService:
    serviceAccount:
      name: "default"
    connectionSecrets: []
    appConfig:
      queryService:
        kafka:
          enabled: false
          tlsUserSecret: ""
          tlsTruststoreSecret: ""
        data:
          connections: []
  secrets:
    authzServiceSecret:
      secretName: ng-manager-ext-secret-0
      key: NEXT_GEN_MANAGER_SECRET
      optional: true
