{{- if .Values.istio.enabled -}}
{{- if .Values.istio.gateway.create -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: public
  namespace: istio-system
spec:
  selector:
     istio: ingressgateway
  servers:
  - port:
      number: {{ .Values.istio.gateway.port }}
      name: https
      protocol: {{ .Values.istio.gateway.protocol }}
    hosts:
    {{- range .Values.istio.hosts }}
    - {{ . | quote }}
    {{- end }}
    {{- with .Values.istio.tls }}
    tls:
      {{- toYaml . | nindent 6 }}
    {{- end }}

{{ end }}
{{ end }}
