apiVersion: v2
appVersion: 0.1.0
dependencies:
- name: registry-api
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.103.0
- name: registry-async-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.60.0
- name: ipqs-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.13.0
- name: registry-processor
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.75.0
description: A Helm chart for Harness Artifact Registry
name: ar
type: application
version: 0.47.0
