apiVersion: v2
appVersion: 0.6.0
dependencies:
- name: chaos-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.70.0-snapshot-2025-12-08-06-00-29-89284a
- name: chaos-web
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.70.0-snapshot-2025-12-08-06-00-29-89284a
- name: chaos-k8s-ifs
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.70.0-snapshot-2025-12-08-06-00-29-89284a
- name: chaos-linux-ifs
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.70.0-snapshot-2025-12-08-06-00-29-587051
- name: chaos-linux-ifc
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.70.0-snapshot-2025-12-08-06-00-29-587051
- name: chaos-crd
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.66.1
- name: chaos-machine-ifs
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.70.0-snapshot-2025-12-08-06-00-29-a27ac3
- name: chaos-machine-ifc
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.70.0-snapshot-2025-12-08-06-00-29-a27ac3
description: A Helm chart for harness chaos module
name: chaos
type: application
version: 0.35.0
