apiVersion: v2
appVersion: 0.6.0
dependencies:
- name: chaos-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.68.6
- name: chaos-web
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.68.3
- name: chaos-k8s-ifs
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.68.4
- name: chaos-linux-ifs
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.68.0
- name: chaos-linux-ifc
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.68.0
- name: chaos-crd
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.67.0
- name: chaos-machine-ifs
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.68.0
- name: chaos-machine-ifc
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.68.1
description: A Helm chart for harness chaos module
name: chaos
type: application
version: 0.34.0
