apiVersion: v2
appVersion: 0.0.79001
dependencies:
- name: sto-core
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.127.5
- name: sto-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.53.0
description: Helm chart for Harness STO
name: sto
type: application
version: 0.26.0
