apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: ff-service
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 0.15.2
- name: ff-pushpin-service
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.1.0
description: A Helm chart for harness Feature Flags module
name: ff
type: application
version: 0.20.0
