apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: ff-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.1145.0
- name: ff-pushpin-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.1128.0-snapshot-2026-01-15-00-00-44-dcdb18
description: A Helm chart for harness Feature Flags module
name: ff
type: application
version: 0.35.4
