{{- if and .Values.global.istio.enabled .Values.global.srm.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: et-collector
spec:
  host: et-collector.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        useSourceIp: true

{{ end }}