{{- if .Values.global.istio.enabled -}}
{{- if .Values.global.istio.gateway.create -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.global.istio.gateway.name | default "public" }}
  namespace: {{ .Values.global.istio.gateway.namespace | default "istio-system" }}
spec:
  selector: {{ toYaml .Values.global.istio.gateway.selector | nindent 4 }}
  servers:
  - port:
      number: {{ .Values.global.istio.gateway.port }}
      name: https
      protocol: {{ .Values.global.istio.gateway.protocol }}
    hosts:
    {{- range .Values.global.istio.hosts }}
    - {{ . | quote }}
    {{- end }}
    {{- with .Values.global.istio.tls }}
    tls:
      {{- toYaml . | nindent 6 }}
    {{- end }}

{{ end }}
{{ end }}
