{{- /*
This ConfigMap contains the global environment variables
*/}}
{{- $previousVersion := "" -}}
{{- with (lookup "v1" "ConfigMap" .Release.Namespace "global-smp-config") -}}
{{- $previousVersion = (get .data "SMP_VERSION" | default "") -}}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-smp-config
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    version: {{ .Chart.Version }}
data:
  SMP_VERSION: {{ .Chart.Version | quote }}
  PREVIOUS_SMP_VERSION: {{ $previousVersion | quote }}
