{{- if .Values.global.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: harness-vs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  gateways:
    {{- if .Values.global.istio.gateway.create }}
    - istio-system/public
    {{- else }}
    {{- range .Values.global.istio.virtualService.gateways }}
    - {{ . }}
    {{- end }}
    {{- end }}
  hosts:
    {{- range .Values.global.istio.virtualService.hosts }}
    - {{ . }}
    {{- end }}
  tcp:
  - match:
    - port: 9000
    route:
    - destination:
        host: log-service-minio
        port:
          number: 9000
  - match:
    - port: 9879
    route:
    - destination:
        host: harness-manager
        port:
          number: 9879
  http:
  - name: ng-manager
    match:
    - uri:
        prefix: /ng/api/
    - uri:
        prefix: /ng/api
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 7090
        host: ng-manager

  - name: et-collector
    match:
    - uri:
        prefix: /et-collector/
    - uri:
        prefix: /et-collector
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 6070
        host: et-collector.{{ .Release.Namespace }}.svc.cluster.local

  - name: et-service
    match:
    - uri:
        prefix: /et/
    - uri:
        prefix: /et
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 9191
        host: et-service

  - name: sto
    match:
    - uri:
        prefix: /sto/
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 4000
        host: sto-core
  - name: sto-manager
    match:
    - uri:
        prefix: /sto-manager/
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 7090
        host: sto-manager
  - name: next-gen-ui
    match:
    - uri:
        prefix: /ng/
    - uri:
        prefix: /ng
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 80
        host: next-gen-ui
  - name: ci-manager
    match:
    - uri:
        prefix: /ci/
    - uri:
        prefix: /ci
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 7090
        host: ci-manager

  - name: cv-nextgen
    match:
    - uri:
        prefix: /cv/
    - uri:
        prefix: /cv
    route:
    - destination:
        port:
          number: 6060
        host: cv-nextgen

  - name: minio-ui
    match:
    - uri:
        prefix: "/minio"
    route:
    - destination:
        port:
          number: 9000
        host: minio

  - name: log-serivce-minio
    match:
    - uri:
        prefix: "/logs/"
    route:
    - destination:
        port:
          number: 9000
        host: minio

  - name: log-service
    match:
    - uri:
        prefix: /log-service//
    - uri:
        prefix: /log-service/
    - uri:
        prefix: /log-service
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 8079
        host: log-service

  # - name: gateway
  #   match:
  #   - uri:
  #       regex: "/gateway(/|$)(.*)"
  #   route:
  #   - destination:
  #       port:
  #         number: 80
  #       host: gateway

  - name: gateway
    match:
    - uri:
        prefix: /gateway/
    - uri:
        prefix: /gateway
    rewrite:
      uri: /
    route:
    - destination:
        host: gateway
        port:
          number: 80

  - name: access-control
    match:
    - uri:
        prefix: /authz/
    - uri:
        prefix: /authz
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 9006
        host: access-control

  - name: ti-service
    match:
    - uri:
        prefix: /ti-service//
    - uri:
        prefix: /ti-service/
    - uri:
        prefix: /ti-service
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 8078
        host: ti-service

  - name: template-service
    match:
    - uri:
        prefix: /template/
    - uri:
        prefix: /template
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 15002
        host: template-service

  - name: delegate-proxy
    match:
    - uri:
        prefix: "/storage"
    route:
    - destination:
        port:
          number: 80
        host: delegate-proxy


  - name: pipeline-service
    match:
    - uri:
        prefix: /pipeline/
    - uri:
        prefix: /pipeline
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 12001
        host: pipeline-service

  - name: notification-service
    match:
    - uri:
        prefix: /notifications/
    - uri:
        prefix: /notifications
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 9005
        host: platform-service

  - name: audit-service
    match:
    - uri:
        prefix: /audit/
    - uri:
        prefix: /audit
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 9005
        host: platform-service

  - name: resourcegroup-service
    match:
    - uri:
        prefix: /resourcegroup/
    - uri:
        prefix: /resourcegroup
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 9005
        host: platform-service

  - name: harness-manager-api
    match:
    - uri:
        #regex: "/api(/|$)(.*)"
        prefix: "/api"
    route:
    - destination:
        port:
          number: 9090
        host: harness-manager

  - name: blocking-swagger-api
    match:
    - uri:
        prefix: /api/swagger
    rewrite:
      uri: /
    route:
    - destination:
        host: dne
        port:
          number: 9999

  - name: harness-manager-stream
    match:
    - uri:
        #regex: "/stream(/|$)(.*)"
        prefix: "/stream"
    route:
    - destination:
        port:
          number: 9090
        host: harness-manager

  - name: grpc-manager
    match:
    - uri:
        prefix: "/"
      port: 9879
    route:
    - destination:
        port:
          number: 9879
        host: harness-manager

  - name: ng-auth-ui
    match:
    - uri:
        prefix: "/auth"
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 80
        host: ng-auth-ui
{{- if .Values.global.ff.enabled }}
  - name: ff-service
    match:
    - uri:
        prefix: /cf/
    - uri:
        prefix: /cf
    rewrite:
      uri: /api/1.0/
    route:
    - destination:
        port:
          number: 16001
        host: ff-service

  - name: ff-pushpin-service
    match:
    - uri:
        prefix: /sdk/
    - uri:
        prefix: /sdk
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 17001
        host: ff-pushpin-service
{{- end }}
{{- if not .Values.global.cg.enabled }}
  - name: harness-ui
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        port:
          number: 80
        host: next-gen-ui
  - name: catchall-redirect
    match:
    - uri:
        regex: ".*"
    redirect:
      uri: "/"
{{- end }}
{{- end }}

