apiVersion: v2
appVersion: 1.16.1
dependencies:
- condition: global.ng.enabled
  name: access-control
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.303.0
- name: bootstrap
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.80.0
- condition: platform.envoy-gateway.enabled
  name: envoy-gateway
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.12.0
- condition: global.cdc.enabled
  name: change-data-capture
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.61.0
- condition: global.ssca.enabled
  name: debezium-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.27.0
- name: delegate-proxy
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.9.0
- name: gateway
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.68.0
- name: harness-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.157.2
- condition: global.ng.enabled
  name: log-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.50.0
- condition: global.ng.enabled
  name: next-gen-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.145.4
- name: ng-auth-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.39.0
- condition: global.ng.enabled
  name: ng-dashboard-aggregator
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.124.0
- condition: global.ng.enabled
  name: ng-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.158.4
- condition: global.ng.enabled
  name: pipeline-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.197.7
- condition: global.ng.enabled
  name: platform-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.140.0
- condition: global.ng.enabled
  name: policy-mgmt
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.59.5
- condition: global.ng.enabled
  name: scm-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.57.0
- condition: global.ng.enabled
  name: template-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.159.0
- condition: global.cg.enabled
  name: ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.36.0
- condition: global.ngcustomdashboard.enabled
  name: ng-custom-dashboards
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.122.0
- condition: global.ngcustomdashboard.enabled
  name: looker
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.24.0
- condition: global.servicediscoverymanager.enabled
  name: service-discovery-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 0.74.1
- condition: global.ng.enabled
  name: audit-event-streaming
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.105.0
- condition: global.ng.enabled
  name: queue-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.11.0
description: Helm chart for Harness Platform
name: platform
type: application
version: 0.44.0
