apiVersion: v2
appVersion: 1.16.1
dependencies:
- condition: global.ng.enabled
  name: access-control
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.105.1
- name: bootstrap
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.53.0
- condition: global.cdc.enabled
  name: change-data-capture
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.46.2
- condition: global.ssca.enabled
  name: debezium-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.21.7
- name: delegate-proxy
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.3.0
- name: gateway
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.56.2-pl-65646-89217a
- name: harness-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.105.3
- condition: global.ng.enabled
  name: log-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.26.3
- condition: global.ng.enabled
  name: next-gen-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.93.7
- name: ng-auth-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.36.1
- condition: global.ng.enabled
  name: ng-dashboard-aggregator
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.70.1
- condition: global.ng.enabled
  name: ng-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.107.6
- condition: global.ng.enabled
  name: pipeline-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.147.3
- condition: global.ng.enabled
  name: platform-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.84.1
- condition: global.ng.enabled
  name: policy-mgmt
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.24.4
- condition: global.ng.enabled
  name: scm-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.40.2
- condition: global.ng.enabled
  name: template-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.109.2
- condition: global.cg.enabled
  name: ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.22.0
- condition: global.ngcustomdashboard.enabled
  name: ng-custom-dashboards
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.87.0
- condition: global.ngcustomdashboard.enabled
  name: looker
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.8.0
- condition: global.servicediscoverymanager.enabled
  name: service-discovery-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 0.45.0
- condition: global.ng.enabled
  name: audit-event-streaming
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.52.1
- condition: global.ng.enabled
  name: queue-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.7.3
description: Helm chart for Harness Platform
name: platform
type: application
version: 0.33.0
