apiVersion: v2
appVersion: 1.16.1
dependencies:
- condition: global.ng.enabled
  name: access-control
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.252.1
- name: bootstrap
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.73.0
- condition: global.cdc.enabled
  name: change-data-capture
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.56.0
- condition: global.ssca.enabled
  name: debezium-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.26.0
- name: delegate-proxy
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.9.0
- name: gateway
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.62.5
- name: harness-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.147.3
- condition: global.ng.enabled
  name: log-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.46.1
- condition: global.ng.enabled
  name: next-gen-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.135.9
- name: ng-auth-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.39.0
- condition: global.ng.enabled
  name: ng-dashboard-aggregator
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.113.0
- condition: global.ng.enabled
  name: ng-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.148.6
- condition: global.ng.enabled
  name: pipeline-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.188.3
- condition: global.ng.enabled
  name: platform-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.128.0
- condition: global.ng.enabled
  name: policy-mgmt
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.50.0
- condition: global.ng.enabled
  name: scm-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.49.0
- condition: global.ng.enabled
  name: template-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.149.0
- condition: global.cg.enabled
  name: ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.36.0
- condition: global.ngcustomdashboard.enabled
  name: ng-custom-dashboards
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.108.0
- condition: global.ngcustomdashboard.enabled
  name: looker
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.14.1
- condition: global.servicediscoverymanager.enabled
  name: service-discovery-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 0.67.2
- condition: global.ng.enabled
  name: audit-event-streaming
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.94.0
- condition: global.ng.enabled
  name: queue-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.10.0
description: Helm chart for Harness Platform
name: platform
type: application
version: 0.41.0
