apiVersion: v2
appVersion: 1.16.1
dependencies:
- condition: global.ng.enabled
  name: access-control
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.70.1
- name: bootstrap
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.23.0
- condition: global.cdc.enabled
  name: change-data-capture
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.41.0
- condition: global.ssca.enabled
  name: debezium-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.21.0
- name: delegate-proxy
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.1.1
- name: gateway
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.41.7
- name: harness-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.68.10
- condition: global.ng.enabled
  name: log-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.17.3
- condition: global.migrator.enabled
  name: migrator
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.116.2
- condition: global.ng.enabled
  name: next-gen-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.58.5
- name: ng-auth-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.32.1
- condition: global.ng.enabled
  name: ng-dashboard-aggregator
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.35.0
- condition: global.ng.enabled
  name: ng-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.72.6
- condition: global.ng.enabled
  name: pipeline-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.111.1
- condition: global.ng.enabled
  name: platform-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.48.0
- condition: global.ng.enabled
  name: policy-mgmt
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.11.1
- condition: global.ng.enabled
  name: scm-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.18.0
- condition: global.ng.enabled
  name: template-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.73.0
- condition: global.cg.enabled
  name: ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.22.0
- condition: global.ngcustomdashboard.enabled
  name: ng-custom-dashboards
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.78.1
- condition: global.ngcustomdashboard.enabled
  name: looker
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.7.2
- condition: global.servicediscoverymanager.enabled
  name: service-discovery-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 0.33.0
- condition: global.ng.enabled
  name: audit-event-streaming
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.17.0
- condition: global.ng.enabled
  name: queue-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.6.1
description: Helm chart for Harness Platform
name: platform
type: application
version: 0.25.3
