apiVersion: v2
appVersion: 1.16.1
dependencies:
- condition: global.ng.enabled
  name: access-control
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.328.0
- name: bootstrap
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.81.0
- condition: platform.envoy-gateway.enabled
  name: envoy-gateway
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.15.0
- condition: global.cdc.enabled
  name: change-data-capture
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.65.0
- condition: global.ssca.enabled
  name: debezium-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.27.0
- name: delegate-proxy
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.9.0
- name: gateway
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.71.0
- name: harness-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.162.1
- condition: global.ng.enabled
  name: log-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.52.1
- condition: global.ng.enabled
  name: next-gen-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.150.3
- name: ng-auth-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.49.0
- condition: global.ng.enabled
  name: ng-dashboard-aggregator
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.129.0
- condition: global.ng.enabled
  name: ng-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.163.5
- condition: global.ng.enabled
  name: pipeline-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.202.2
- condition: global.ng.enabled
  name: platform-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.145.0
- condition: global.ng.enabled
  name: policy-mgmt
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.64.0
- condition: global.ng.enabled
  name: scm-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.62.0
- condition: global.ng.enabled
  name: template-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.164.0
- condition: global.cg.enabled
  name: ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.36.3
- condition: global.ngcustomdashboard.enabled
  name: ng-custom-dashboards
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.124.0
- condition: global.ngcustomdashboard.enabled
  name: looker
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.28.3
- condition: global.servicediscoverymanager.enabled
  name: service-discovery-manager
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 0.79.0
- condition: global.ng.enabled
  name: audit-event-streaming
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.110.1
- condition: global.ng.enabled
  name: queue-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.13.0
- condition: global.dbopsHelmMigration.enabled
  name: harness-db-migrator
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 2.5.0
description: Helm chart for Harness Platform
name: platform
type: application
version: 0.45.0
