apiVersion: v2
appVersion: 1.16.1
dependencies:
- condition: global.ng.enabled
  name: access-control
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.56.1
- name: bootstrap
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.9.0
- condition: global.cdc.enabled
  name: change-data-capture
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.25.1
- condition: global.ssca.enabled
  name: debezium-service
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.16.1
- name: delegate-proxy
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 0.12.0
- name: gateway
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.31.2
- name: harness-manager
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.42.5
- condition: global.ng.enabled
  name: log-service
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.9.2
- condition: global.migrator.enabled
  name: migrator
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.107.0
- condition: global.ng.enabled
  name: next-gen-ui
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.37.5
- name: ng-auth-ui
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.27.0
- condition: global.ng.enabled
  name: ng-dashboard-aggregator
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.28.0
- condition: global.ng.enabled
  name: ng-manager
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.51.9
- condition: global.ng.enabled
  name: pipeline-service
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.89.2
- condition: global.ng.enabled
  name: platform-service
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.34.2
- condition: global.ng.enabled
  name: policy-mgmt
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.8.2
- condition: global.ng.enabled
  name: scm-service
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.7.1
- condition: global.ng.enabled
  name: template-service
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.51.0
- condition: global.cg.enabled
  name: ui
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.22.0
- condition: global.ngcustomdashboard.enabled
  name: ng-custom-dashboards
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.69.0
- condition: global.ngcustomdashboard.enabled
  name: looker
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.1.0
- condition: global.servicediscoverymanager.enabled
  name: service-discovery-manager
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 0.21.1
- condition: global.ng.enabled
  name: audit-event-streaming
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.9.0
- condition: global.ng.enabled
  name: queue-service
  repository: oci://us-west1-docker.pkg.dev/platform-205701/harness-qa-artifacts
  version: 1.2.0
description: Helm chart for Harness Platform
name: platform
type: application
version: 0.20.2
