apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: global.idp.enabled
  name: idp-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.37.1-snapshot-2026-02-18-18-00-32-9885d0
- condition: global.idp.enabled
  name: idp-admin
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.37.1-snapshot-2026-02-18-18-00-32-a5fd27
- condition: global.idp.enabled
  name: idp-app-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.34.5
description: A Helm chart for Harness IDP
name: idp
type: application
version: 0.35.8
