apiVersion: v2
appVersion: 1.16.0
dependencies:
- condition: global.idp.enabled
  name: idp-service
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.33.11-snapshot-2025-11-13-11-25-59-70791e
- condition: global.idp.enabled
  name: idp-admin
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.33.2-snapshot-2025-11-13-11-25-59-7bcc1f
- condition: global.idp.enabled
  name: idp-app-ui
  repository: oci://us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts
  version: 1.32.13
description: A Helm chart for Harness IDP
name: idp
type: application
version: 0.34.0
