name: Release chart-testing

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTION"
          git config user.email "$GITHUB_ACTION@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Add Helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run Chart Releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: src
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
