name: Release chart demo and prod

on:
  workflow_run:
    workflows: ["Release chart harness"]
    types:
      - completed

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTION"
          git config user.email "$GITHUB_ACTION@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - name: Add Helm repos
        run: |
          helm repo add harness-gitops https://harness.github.io/helm-gitops
          helm repo add harness-policy-mgmt https://harness.github.io/helm-policy-mgmt
          helm repo add harness-helm https://harness.github.io/helm-charts
          helm repo add harness-common https://harness.github.io/helm-common
          helm repo add harness-sto https://harness.github.io/helm-sto
          helm repo add harness-dashboards https://harness.github.io/helm-dashboards
          helm repo add harness-platform https://harness.github.io/helm-platform
          helm repo add harness-ccm https://harness.github.io/helm-ccm
          helm repo add harness-ff https://harness.github.io/helm-ff
          helm repo add harness-srm https://harness.github.io/helm-srm
          helm repo add harness-chaos https://harness.github.io/helm-chaos
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Install yq
        uses: dcarbone/install-yq-action@v1.3.0
        with:
          version: 'v4.28.1'

      - name: Backup values.yaml and Chart.yaml
        run: |
          cp src/harness/values.yaml harness-values.yaml
          cp src/harness/Chart.yaml harness-chart.yaml

      - name: Override values.yaml and Chart.yaml for demo
        run: |
          yq '. *= load("src/override-demo.yaml")' harness-values.yaml > tmp.values
          mv tmp.values src/harness/values.yaml
          yq '.name += "-demo"' harness-chart.yaml > src/harness/Chart.yaml

      - name: Run Chart Releaser demo
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: src
        env:
          CR_SKIP_EXISTING: true
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NOTES_FILE: images.txt

      - name: Override values.yaml and Chart.yaml for prod
        run: |
          yq '. *= load("src/override-prod.yaml")' harness-values.yaml > tmp.values
          mv tmp.values src/harness/values.yaml
          yq '.name += "-prod"' harness-chart.yaml > src/harness/Chart.yaml

      - name: Run Chart Releaser prod
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: src
        env:
          CR_SKIP_EXISTING: true
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NOTES_FILE: images.txt
